name: WorldManagement
main: crytec.worldmanagement.WorldManagerPlugin
version: 1.0.1
author: crysis992
description: CryTec World Management Plugin
api-version: 1.13

commands:
    worldmanagement:
        description: Access to WorldManagement Commands
        aliases: [wm]
        usage: Syntax error! Simply type /wm;