name: WorldManagement
main: crytec.worldmanagement.WorldManagerPlugin
version: 1.0.3
author: crysis992
description: CryTec World Management Plugin
api-version: 1.13

commands:
    worldmanagement:
        description: Access to WorldManagement Commands
        aliases: [wm]
        usage: Syntax error! Simply type /wm;
        

permissions:  
  worldmanagement.gamemode.bypass:
    description: Allows the player to bypass the gamemode restriction
    default: op
  worldmanagement.teleport:
    description: Allows the player to teleport directly to worlds via command.
    default: op
  worldmanagement.admin:
    description: Grants access to all functions of the plugin
    default: op
    children:
      worldmanagement.teleport: true
      worldmanagement.gamemode.bypass: true